# Generated by Django 6.0 on 2025-12-28 12:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(default='Loyalty Program', max_length=100, verbose_name='Program Name')),
                ('program_enabled', models.BooleanField(default=True, verbose_name='Program Enabled')),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Points earned per currency unit spent (e.g., 1 point per €1)', max_digits=10, verbose_name='Points per Currency Unit')),
                ('points_value', models.DecimalField(decimal_places=4, default=Decimal('0.01'), help_text='Currency value of each point when redeemed', max_digits=10, verbose_name='Point Value')),
                ('minimum_redemption', models.PositiveIntegerField(default=100, help_text='Minimum points required to redeem', verbose_name='Minimum Points for Redemption')),
                ('points_expire', models.BooleanField(default=False, verbose_name='Points Expire')),
                ('expiry_months', models.PositiveIntegerField(default=12, help_text='Months after earning before points expire', verbose_name='Expiry Period (Months)')),
                ('auto_enroll', models.BooleanField(default=True, help_text='Automatically enroll customers on first purchase', verbose_name='Auto-Enroll Customers')),
                ('welcome_points', models.PositiveIntegerField(default=0, help_text='Bonus points given on enrollment', verbose_name='Welcome Points')),
                ('show_points_on_receipt', models.BooleanField(default=True, verbose_name='Show Points on Receipt')),
                ('show_available_rewards', models.BooleanField(default=True, verbose_name='Show Available Rewards at Checkout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Configuration',
                'verbose_name_plural': 'Loyalty Configuration',
                'db_table': 'loyalty_config',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_es', models.CharField(blank=True, max_length=50, verbose_name='Name (Spanish)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='star-outline', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(default='#cd7f32', max_length=7, verbose_name='Color')),
                ('min_points', models.PositiveIntegerField(default=0, help_text='Points required to reach this tier', verbose_name='Minimum Points')),
                ('min_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total spent required to reach this tier', max_digits=12, verbose_name='Minimum Spent')),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier for points earned (e.g., 1.5 = 50% more points)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Points Multiplier')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Automatic discount for this tier', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount %')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Free Shipping')),
                ('exclusive_offers', models.BooleanField(default=False, verbose_name='Exclusive Offers')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_default', models.BooleanField(default=False, help_text='Tier assigned to new members', verbose_name='Default Tier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Tier',
                'verbose_name_plural': 'Loyalty Tiers',
                'db_table': 'loyalty_tier',
                'ordering': ['order', 'min_points'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=20, unique=True, verbose_name='Member Number')),
                ('card_number', models.CharField(blank=True, help_text='Physical or digital card number', max_length=30, null=True, unique=True, verbose_name='Card Number')),
                ('customer_id', models.PositiveIntegerField(blank=True, help_text='ID from customers module', null=True, verbose_name='Customer ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('points_balance', models.PositiveIntegerField(default=0, verbose_name='Points Balance')),
                ('lifetime_points', models.PositiveIntegerField(default=0, verbose_name='Lifetime Points Earned')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Spent')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='Visit Count')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity')),
                ('last_purchase_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Purchase')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='loyalty.loyaltytier', verbose_name='Tier')),
            ],
            options={
                'verbose_name': 'Loyalty Member',
                'verbose_name_plural': 'Loyalty Members',
                'db_table': 'loyalty_member',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_es', models.CharField(blank=True, max_length=100, verbose_name='Name (Spanish)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='gift-outline', max_length=50, verbose_name='Icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='loyalty/rewards/', verbose_name='Image')),
                ('points_cost', models.PositiveIntegerField(help_text='Points required to redeem', verbose_name='Points Cost')),
                ('reward_type', models.CharField(choices=[('discount_percent', 'Discount %'), ('discount_amount', 'Discount Amount'), ('free_product', 'Free Product'), ('free_shipping', 'Free Shipping'), ('gift_card', 'Gift Card')], default='discount_amount', max_length=20, verbose_name='Reward Type')),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount % or amount, or product value', max_digits=10, verbose_name='Value')),
                ('product_id', models.PositiveIntegerField(blank=True, help_text='For free product rewards', null=True, verbose_name='Product ID')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='Product Name')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Total times this can be redeemed (null = unlimited)', null=True, verbose_name='Max Redemptions')),
                ('max_per_member', models.PositiveIntegerField(default=1, help_text='Times each member can redeem', verbose_name='Max Per Member')),
                ('times_redeemed', models.PositiveIntegerField(default=0, verbose_name='Times Redeemed')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_tier', models.ForeignKey(blank=True, help_text='Minimum tier required to redeem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_rewards', to='loyalty.loyaltytier', verbose_name='Minimum Tier')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'db_table': 'loyalty_reward',
                'ordering': ['order', '-is_featured', 'points_cost'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earn', 'Points Earned'), ('redeem', 'Points Redeemed'), ('bonus', 'Bonus Points'), ('adjust', 'Manual Adjustment'), ('expire', 'Points Expired'), ('tier', 'Tier Change'), ('return', 'Return Deduction')], max_length=20, verbose_name='Type')),
                ('points', models.IntegerField(help_text='Positive for earned, negative for redeemed/expired', verbose_name='Points')),
                ('balance_after', models.PositiveIntegerField(verbose_name='Balance After')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('sale_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sale ID')),
                ('processed_by', models.CharField(blank=True, max_length=255, verbose_name='Processed By')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltymember', verbose_name='Member')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loyalty.reward', verbose_name='Reward')),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'verbose_name_plural': 'Points Transactions',
                'db_table': 'loyalty_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Redemption Code')),
                ('points_used', models.PositiveIntegerField(verbose_name='Points Used')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('reward_type', models.CharField(max_length=20, verbose_name='Reward Type')),
                ('reward_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Reward Value')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('sale_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Applied to Sale')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.loyaltymember', verbose_name='Member')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.reward', verbose_name='Reward')),
            ],
            options={
                'verbose_name': 'Reward Redemption',
                'verbose_name_plural': 'Reward Redemptions',
                'db_table': 'loyalty_redemption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loyaltymember',
            index=models.Index(fields=['member_number'], name='loyalty_mem_member__9c62a6_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltymember',
            index=models.Index(fields=['card_number'], name='loyalty_mem_card_nu_ddedb4_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltymember',
            index=models.Index(fields=['customer_id'], name='loyalty_mem_custome_4f7b13_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltymember',
            index=models.Index(fields=['email'], name='loyalty_mem_email_974a49_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltymember',
            index=models.Index(fields=['phone'], name='loyalty_mem_phone_f6963b_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['member', '-created_at'], name='loyalty_tra_member__ec25a1_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['transaction_type'], name='loyalty_tra_transac_2d61e5_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['sale_id'], name='loyalty_tra_sale_id_fd61ee_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['code'], name='loyalty_red_code_dc18bc_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['member', '-created_at'], name='loyalty_red_member__4b47dc_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['status'], name='loyalty_red_status_5232b9_idx'),
        ),
    ]
